abbr -q g='git'
abbr -q ga='git add'
abbr -q gaa='git add --all'
abbr -q gap='git add --patch'
abbr -q gb='git branch'
abbr -q gbd='git branch --delete --force'
abbr -q gbm='git branch --move'
abbr -q gc='git commit'
abbr -q gca='git commit --amend'
abbr -q gcan='git commit --amend --no-edit'
abbr -q gcm='git commit --message'
abbr -q gcle='git clean -d --force'
abbr -q gclo='git clone'
abbr -q gco='git checkout'
abbr -q gcob='git checkout -b'
# Remove "+" and "-" from start of diff lines; just rely upon color.
abbr -q gd='git diff --color | sed "s/^\([^-+ ]*\)[-+ ]/\\1/" | less -r'
abbr -q gf='git fetch'
abbr -q gfa='git fetch --all'
abbr -q gl='git log --graph --pretty=format:"%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset" --abbrev-commit --date=relative'
abbr -q gpl='git pull'
abbr -q gps='git push'
abbr -q grb='git rebase'
abbr -q grs='git reset'
abbr -q gs='git status --short --branch'
