name: shellcheck

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get changed shell files
        id: sh-changed
        run: |
          changed_files=$(git diff ${{ github.event.pull_request.base.sha }}.. --name-only --diff-filter=AM -- '*.sh')
          delimiter="$(openssl rand -hex 8)"
          echo "files<<${delimiter}" >> $GITHUB_OUTPUT
          echo "$changed_files" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT
          echo "Changed shell files: $changed_files"
      - name: Run shellcheck
        if: steps.sh-changed.outputs.files != ''
        run: |
          for file in ${{ steps.sh-changed.outputs.files }}; do
            echo "Checking $file"
            shellcheck -x "$file"
          done
